### ISSUE TITLE
Embed/distribute plantuml.jar

### ISSUE THREAD

**Issue by lodahl** [lodahl/Libo_PlantUML#4]
To avoid dependencies.
I must check license compliance first!!!!!¨

**Comment by pascalpoizat** [comment]
Hello,
wouldn't this require to update the plugin each time PlantUML is updated?
Indeed we still have the graphviz dependency so it is not so much an issue.
What could help the basic user is an installation script to install graphviz+plantuml+Libo_plantuml.
Indeed under OSX we already have a script to install graphviz+plantuml at a time. Libo_plantuml still requires to find plantuml.jar in a given directory (I added it for OSX) instead of looking it in the class path I think).
